---
spring:
  profiles:
    active: local
    group:
      local: profiles-local
        , profile-console
        , log-level-local
      dev: profiles-dev
        , profile-file
        , log-level-dev

---
spring:
  config:
    activate:
      on-profile: "profiles-local"
    import:
      classpath:config/environment/environment-local.yml

---
spring:
  config:
    activate:
      on-profile: "profiles-dev"
    import:
      classpath:config/environment/environment-dev.yml
